server:
  context-path: /springboot
  port: 8989
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  mapper-locations: classpath:com/baizhi/wcj/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.wcj.entity