#server:
#  context-path: /springbootDev
#  jsp-servlet:
#    init-parameters:
#     development: true
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ems
#    username: root
#    password: root
#  mvc:
#    view:
#      prefix: /
#      suffix: .jsp
#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.baizhi.wcj.entity